#!/bin/sh

# Generate a new identity keypair and upload the public key to firestore
# Ensure you have FIREBASE_API_KEY set in your environment
set -eu

hostname="$1"
firebase_project="$2"
identity_path="$3"

if [ -z "$hostname" ]; then
	echo "Error: No hostname specified." 1>&2;
	exit 1
fi

if [ -z "$firebase_project" ]; then
	echo "Error: No firebase project specified." 1>&2;
	exit 1
fi

if [ -z "$identity_path" ]; then
	echo "Error: No target directory for identity path specified." 1>&2;
	exit 1
fi
if [ -z "$YB_FIREBASE_API_KEY" ]; then
	echo "Error: No YB_FIREBASE_API_KEY specified." 1>&2;
	exit 1
fi

# Set up keypair for firebase login
mkdir -p "$identity_path"
openssl genpkey -algorithm ed25519 -out "$identity_path/private_key.pem"
openssl pkey -in "$identity_path/private_key.pem" -pubout -out "$identity_path/public_key.pem"
gcloud_access_token=$(gcloud auth print-access-token)

# Upload the public key and nonce to firestore
curl -X PATCH "https://firestore.googleapis.com/v1/projects/$firebase_project/databases/(default)/documents/controller_identity/$hostname?updateMask.fieldPaths=publicKey,nonce&key=$YB_FIREBASE_API_KEY" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $gcloud_access_token" \
  -d "{\"fields\": {\"publicKey\": {\"stringValue\": \"$(cat $identity_path/public_key.pem)\"}, \"nonce\": {\"stringValue\": \"$(openssl rand -base64 16)\"}}}"

echo "Set up device identity"